In [93]:
import numpy as np

# Task 1

In [94]:
np.array(range(1, 11))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Task 2

In [95]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Task 3

In [96]:
np.random.randint(1, 11, size=(5, 5))

array([[ 9,  1,  5,  3,  3],
       [ 5,  2,  4,  5, 10],
       [ 9,  9,  9,  9,  9],
       [ 3,  2,  8, 10,  4],
       [10,  6,  4,  6,  4]])

# Task 4

In [97]:
np.random.random((4, 4))

array([[0.96011234, 0.49504345, 0.76584914, 0.61310034],
       [0.40222339, 0.71784171, 0.31903439, 0.45192319],
       [0.0495314 , 0.03264625, 0.8916847 , 0.23632208],
       [0.17734195, 0.77393251, 0.5153459 , 0.97979243]])

# Task 5

In [98]:
v1 = np.random.randint(1, 11, size=(5,))
v2 = np.random.randint(1, 11, size=(5,))

print(v1)
print(v2)
print(v1+v2)
print(v1-v2)
print(v1*v2)

[ 2  9  6  3 10]
[9 1 5 3 5]
[11 10 11  6 15]
[-7  8  1  0  5]
[18  9 30  9 50]


# Task 6

In [99]:
v1 = np.random.randint(1, 11, size=(5,))
v2 = np.random.randint(1, 11, size=(5,))

print(v1)
print(v2)
print(np.dot(v1, v2))

[8 6 7 3 9]
[4 3 2 9 8]
163


# Task 7

In [100]:
v1 = np.random.randint(1, 11, size=(2,2))
v2 = np.random.randint(1, 11, size=(2,3))

print(v1)
print(v2)
print(np.dot(v1, v2))


[[6 8]
 [7 8]]
[[ 4  2 10]
 [ 1  4  2]]
[[32 44 76]
 [36 46 86]]


# Task 8

In [101]:
v1 = np.random.randint(1, 11, size=(3,3))
print(v1)
np.linalg.inv(v1)

[[ 5  6  1]
 [ 1  5  7]
 [10  7  2]]


array([[-2.29411765e-01, -2.94117647e-02,  2.17647059e-01],
       [ 4.00000000e-01, -1.67065024e-18, -2.00000000e-01],
       [-2.52941176e-01,  1.47058824e-01,  1.11764706e-01]])

# Task 9

In [102]:
v1 = np.random.random(size=(4,4))
print(v1)
v1.T

[[0.66545069 0.1189218  0.46651723 0.19281336]
 [0.20075904 0.41294686 0.07524563 0.17900786]
 [0.34034171 0.13886439 0.09970679 0.05438153]
 [0.22714155 0.79733494 0.65056602 0.28791562]]


array([[0.66545069, 0.20075904, 0.34034171, 0.22714155],
       [0.1189218 , 0.41294686, 0.13886439, 0.79733494],
       [0.46651723, 0.07524563, 0.09970679, 0.65056602],
       [0.19281336, 0.17900786, 0.05438153, 0.28791562]])

# Task 10

In [103]:
v1 = np.random.randint(1, 11, size=(3,4))
v2 = np.random.randint(1, 11, size=(4,))

print(v1)
print(v2)
print(np.dot(v1,v2))

[[ 9  9  4  8]
 [10  2  7  8]
 [ 1  5  7  1]]
[9 3 6 1]
[140 146  67]


# Task 11

In [104]:
v1 = np.random.random(size=(2,3))
v2 = np.random.random(size=(3,))

print(v1)
print(v2)
print(np.dot(v1,v2))

[[0.9739978  0.3038662  0.91506447]
 [0.04789496 0.6180743  0.35306321]]
[0.89508917 0.08201613 0.34690511]
[1.21417735 0.21604176]


# Task 12

In [105]:
v1 = np.random.randint(1, 11, size=(2,2))
v2 = np.random.randint(1, 11, size=(2,2))

print(v1)
print(v2)
print(v1 * v2)

[[9 8]
 [9 2]]
[[2 3]
 [3 3]]
[[18 24]
 [27  6]]


# Task 13

In [106]:
v1 = np.random.randint(1, 11, size=(2,2))
v2 = np.random.randint(1, 11, size=(2,2))

print(v1)
print(v2)
print(np.dot(v1, v2))

[[4 4]
 [4 6]]
[[2 8]
 [6 9]]
[[32 68]
 [44 86]]


# Task 14

In [107]:
np.random.randint(1, 101, size=(5,5)).sum()

1093

# Task 15

In [108]:
v1 = np.random.randint(1, 11, size=(4,4))
v2 = np.random.randint(1, 11, size=(4,4))

print(v1)
print(v2)
print(v1-v2)

[[ 2 10  7  6]
 [ 5 10  6  1]
 [ 6  3  9  7]
 [10  9  7  3]]
[[ 3  8  3  1]
 [10 10  2  3]
 [ 1 10  7  4]
 [ 8  7  6  4]]
[[-1  2  4  5]
 [-5  0  4 -2]
 [ 5 -7  2  3]
 [ 2  2  1 -1]]


# Task 16

In [109]:
v = np.random.random((3,3))
print(v)
print(np.array([
    v[0].sum(),
    v[1].sum(),
    v[2].sum(),
    ]))

print(v.sum(axis=1))

[[0.96704187 0.80249394 0.84918497]
 [0.40659153 0.4077127  0.51711212]
 [0.12473655 0.19198451 0.47499859]]
[2.61872079 1.33141635 0.79171965]
[2.61872079 1.33141635 0.79171965]


# Task 17

In [110]:
v = np.random.randint(1,11,size=(3,4))
print(v)
np.power(v,2)



[[10  2  1  8]
 [ 1  5  1  9]
 [ 6  6  6  2]]


array([[100,   4,   1,  64],
       [  1,  25,   1,  81],
       [ 36,  36,  36,   4]], dtype=int32)

# Task 18

In [111]:
v = np.random.randint(1,51,size=(4,))
print(v)
np.sqrt(v)

[48 21 27 46]


array([6.92820323, 4.58257569, 5.19615242, 6.78232998])